name: 'Dev version'
description: 'Creates a dev version'
branding:
  color: orange
  icon: anchor
inputs:
  branch:
    description: 'Branch of current execution'
    required: false
    default: 'master'
  filePath:
    description: 'Path to json file with version key'
    required: false
    default: 'package.json'
outputs:
  version:
    description: 'New generated version number'
runs:
  using: 'node12'
  main: 'dist/index.js'
